// <auto-generated />
using System;
using DotNetCoreWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetCoreWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240105210921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetCoreWebAPI.Models.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Color = "Black",
                            Gender = "men",
                            Price = 29.989999999999998,
                            Size = 7
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Addidas",
                            Color = "Yellow",
                            Gender = "women",
                            Price = 59.990000000000002,
                            Size = 10
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Atletics",
                            Color = "Brown",
                            Gender = "men",
                            Price = 19.989999999999998,
                            Size = 9
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Puma",
                            Color = "White",
                            Gender = "women",
                            Price = 39.990000000000002,
                            Size = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
